import React, { useState } from 'react';
import { downloadHtmlFile } from '../utils/validation';
import type { ReportViewerProps } from '../types';

export const ReportViewer: React.FC<ReportViewerProps> = ({ htmlContent, reportId }) => {
  const [isFullscreen, setIsFullscreen] = useState(false);

  const toggleFullscreen = () => {
    setIsFullscreen(!isFullscreen);
  };

  const handleDownload = () => {
    downloadHtmlFile(htmlContent, reportId);
  };

  return (
    <div className="max-w-6xl mx-auto">
      <div className="bg-white rounded-lg shadow-lg border border-gray-200">
        {/* Header */}
        <div className="border-b border-gray-200 px-6 py-4">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-xl font-semibold text-gray-900">
                Tax Report Generated Successfully
              </h2>
              <p className="text-sm text-gray-600 mt-1">
                Report ID: <code className="bg-gray-100 px-2 py-1 rounded text-xs">{reportId}</code>
              </p>
            </div>
            
            <div className="flex items-center space-x-3">
              {/* Download button */}
              <button
                onClick={handleDownload}
                className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-md text-sm font-medium transition-colors flex items-center space-x-2"
              >
                <span>📥</span>
                <span>Download HTML</span>
              </button>
              
              {/* Fullscreen toggle */}
              <button
                onClick={toggleFullscreen}
                className="bg-gray-100 hover:bg-gray-200 text-gray-700 px-4 py-2 rounded-md text-sm font-medium transition-colors"
              >
                {isFullscreen ? (
                  <span className="flex items-center space-x-2">
                    <span>🗗</span>
                    <span>Exit Fullscreen</span>
                  </span>
                ) : (
                  <span className="flex items-center space-x-2">
                    <span>⛶</span>
                    <span>Fullscreen</span>
                  </span>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className={`
          relative bg-gray-50
          ${isFullscreen ? 'fixed inset-0 z-50 bg-white' : 'rounded-b-lg'}
        `}>
          {/* Close button for fullscreen */}
          {isFullscreen && (
            <button
              onClick={toggleFullscreen}
              className="absolute top-4 right-4 z-10 bg-red-500 hover:bg-red-600 text-white px-3 py-2 rounded-md text-sm font-medium"
            >
              ✕ Close
            </button>
          )}

          {/* iframe with report */}
          <iframe
            srcDoc={htmlContent}
            sandbox="allow-scripts allow-same-origin allow-forms allow-popups"
            className={`
              w-full border-0
              ${isFullscreen ? 'h-screen' : 'h-[80vh]'}
            `}
            title="Fiscal Wizard Tax Report"
          />
        </div>

        {/* Footer info */}
        {!isFullscreen && (
          <div className="border-t border-gray-200 px-6 py-4 bg-gray-50">
            <div className="flex items-center justify-between text-sm text-gray-600">
              <div>
                <p>Generated by Fiscal Wizard - Spanish IRPF Calculator</p>
                <p className="text-xs mt-1">
                  Report contains official Spanish tax form boxes (casillas fiscales)
                </p>
              </div>
              
              <div className="text-right">
                <p className="font-medium text-gray-900">Interactive Brokers</p>
                <p className="text-xs">Tax Year 2024</p>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};